name: ai-script-inventory
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    # Core runtime dependencies (pinned versions)
    - spacy==3.8.7
    - pyyaml==6.0.2
    - openai==1.59.0
    
    # Testing dependencies  
    - pytest==8.3.3
    - pytest-cov==6.0.0
    
    # Development tools
    - black==24.10.0
    - isort==5.13.2
    - flake8==7.1.1
    - mypy==1.13.0
    
    # Security and quality tools
    - bandit==1.8.0
    - safety==3.2.11
    - pre-commit==4.0.1
    - pylint==3.3.1
    
    # Python version compatibility
    - tomli==2.1.0; python_version<"3.11"
    - toml==0.10.2