name: ai-script-inventory
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    # Core runtime dependencies
    - spacy>=3.8.0,<4.0.0
    - pyyaml>=6.0.0,<7.0.0
    - openai>=1.0.0
    
    # Testing dependencies  
    - pytest>=8.0.0
    - pytest-cov>=5.0.0
    
    # Development tools
    - black>=24.0.0
    - isort>=5.13.0
    - flake8>=7.0.0
    - mypy>=1.8.0
    
    # Security and quality tools
    - bandit>=1.8.0
    - safety>=3.0.0
    - pre-commit>=4.0.0
    - pylint>=3.0.0
    
    # Python version compatibility
    - tomli>=2.0.0; python_version<"3.11"
    - toml>=0.10.0