name: 📚 Documentation Issue
description: Report issues with documentation or suggest improvements
title: "[DOCS]: "
labels: ["documentation", "triage"]
assignees:
  - JLWard429
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve our documentation! Clear documentation is essential for a great developer experience.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation issue is this?
      options:
        - Error/Inaccuracy
        - Missing Information
        - Unclear Instructions
        - Outdated Content
        - New Documentation Needed
        - Formatting/Presentation Issue
        - Other
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Documentation Location
      description: Where is the documentation issue located?
      placeholder: |
        - File: README.md
        - Section: Installation
        - Line: 25-30
        - URL: https://github.com/JLWard429/ai-script-inventory-/blob/main/docs/...
    validations:
      required: true

  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: Describe the documentation issue in detail
      placeholder: What specifically is wrong, missing, or unclear?
    validations:
      required: true

  - type: textarea
    id: expected-content
    attributes:
      label: Expected Content
      description: What should the documentation say instead?
      placeholder: Provide the correct or improved content

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: How does this documentation issue affect users?
      placeholder: |
        - Prevents users from completing [task]
        - Causes confusion about [topic]
        - Makes it difficult to [action]

  - type: dropdown
    id: audience
    attributes:
      label: Target Audience
      description: Who is affected by this documentation issue?
      options:
        - New Users/Beginners
        - Experienced Users
        - Developers/Contributors
        - System Administrators
        - All Users
    validations:
      required: true

  - type: textarea
    id: suggested-improvement
    attributes:
      label: Suggested Improvement
      description: How would you improve this documentation?
      placeholder: |
        - Add examples for [topic]
        - Include step-by-step instructions for [process]
        - Add troubleshooting section for [common issues]
        - Update screenshots/images
        - Reorganize content structure

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help improve this documentation?
      options:
        - label: I am willing to submit a pull request to fix this documentation
        - label: I can provide additional examples or use cases
        - label: I can help review improved documentation

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/JLWard429/ai-script-inventory-/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true