name: 🔒 Security Issue
description: Report a security vulnerability (for non-sensitive issues only)
title: "[SECURITY]: "
labels: ["security", "critical"]
assignees:
  - JLWard429
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ Security Issue Reporting
        
        **IMPORTANT**: If you believe you have found a serious security vulnerability, please **DO NOT** open a public issue. 
        Instead, please contact us privately at [security contact info] or use GitHub's security advisory feature.
        
        This template is only for non-sensitive security improvements or general security-related issues.

  - type: dropdown
    id: security-type
    attributes:
      label: Security Issue Type
      description: What type of security issue is this?
      options:
        - Dependency Vulnerability (Low/Medium Risk)
        - Configuration Improvement
        - Security Best Practice
        - Permissions Issue
        - Security Documentation
        - Security Testing
        - Other (Non-sensitive)
    validations:
      required: true

  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: Describe the security issue or improvement needed
      placeholder: Please provide a clear description of the security concern or improvement
    validations:
      required: true

  - type: textarea
    id: affected-components
    attributes:
      label: Affected Components
      description: Which parts of the system are affected?
      placeholder: |
        - GitHub Workflows
        - Python Scripts
        - Shell Scripts
        - Dependencies
        - Configuration Files
    validations:
      required: true

  - type: dropdown
    id: risk-level
    attributes:
      label: Risk Level
      description: What is the risk level of this issue?
      options:
        - Low (Informational/Best Practice)
        - Medium (Potential Security Improvement)
        - High (Should be addressed soon)
        - Critical (Requires immediate attention)
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce/Verify
      description: How can this security issue be reproduced or verified?
      placeholder: |
        1. Step one
        2. Step two
        3. Observe security issue

  - type: textarea
    id: suggested-fix
    attributes:
      label: Suggested Fix/Improvement
      description: How do you suggest fixing or improving this security issue?
      placeholder: Describe your recommended solution or improvement

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any additional information, references, or context

  - type: checkboxes
    id: verification
    attributes:
      label: Verification
      description: Please confirm the following
      options:
        - label: This is NOT a sensitive security vulnerability that could be exploited
          required: true
        - label: I have checked that this issue hasn't been reported already
          required: true
        - label: I understand that sensitive security issues should be reported privately
          required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/JLWard429/ai-script-inventory-/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true